/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
	export interface GlobalComponents {
		NButton: (typeof import("naive-ui"))["NButton"];
		NInput: (typeof import("naive-ui"))["NInput"];
		NMessageProvider: (typeof import("naive-ui"))["NMessageProvider"];
		NPopconfirm: (typeof import("naive-ui"))["NPopconfirm"];
		NSlider: (typeof import("naive-ui"))["NSlider"];
		NSpace: (typeof import("naive-ui"))["NSpace"];
		NSpin: (typeof import("naive-ui"))["NSpin"];
		NTooltip: (typeof import("naive-ui"))["NTooltip"];
		RouterLink: (typeof import("vue-router"))["RouterLink"];
		RouterView: (typeof import("vue-router"))["RouterView"];
	}
}
